name: domain
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

resolution: workspace

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  vaden_core:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
