name: vaden_ai
description: A Dart package for ai-related functionalities. Vaden is a Backend Framework Using Dart.
version: 1.0.0
repository: https://github.com/Flutterando/vaden

resolution: workspace

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  vaden: ^0.0.12
  result_dart: ^2.0.0
 # dart_mcp: ^0.2.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
