name: frontend
description: "Vaden Generator"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  #System Features
  auto_injector: ^2.1.0
  provider: ^6.1.2
  result_dart: ^2.0.0
  result_command: ^1.3.0
  
  #Services
  http: ^1.3.0
  dio: ^5.8.0+1
  url_launcher: ^6.3.1

  #Designer
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1

  #Internation
  flutter_localizations: 
    sdk: flutter
  localization: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logo/
    - assets/bg/
    - lib/i18n/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
